### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/gabrielamartinezch-Instagram-Post-Layout#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen trabajo. Felicidades @gabrielamartinezch   !
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Sería recomendable que en el `<head>` incluyeras 
`<meta charset="UTF-8">` 
y
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

La etiqueta `<meta charset="UTF-8">` especifica el conjunto de caracteres UTF-8 para el documento HTML. Si no se especifica, el navegador utilizará un conjunto de caracteres por defecto, que puede no ser UTF-8. Es una buena práctica incluir esta etiqueta para asegurarse de que los caracteres especiales se muestren correctamente.

La etiqueta `<meta name="viewport" content="width=device-width, initial-scale=1.0">` es importante para garantizar que tu sitio web se muestre correctamente en dispositivos móviles.

**Comment by gabrielamartinezch** [comment]
Hola, Edo:
Gracias por tus comentarios.
Me queda una duda respecto a la etiqueta que me recomiendas incluir en el <head>: ¿debo agregarlo en todos los ejercicios?
Un saludo,
Gabriela

**Comment by gabrielamartinezch** [comment]
me borró la etiqueda de head en el comentario anterior

**Comment by EduardoHernandezGuzman** [comment]
Sería recomendable que las uses en tus proyectos.
En codespaces si escribes `!` verás que te rellena la estructura básica de un index.html, incluyendo esas etiquetas que te comento.
Salvo ese pequeño detalle, muy buen trabajo Gabriela.

**Comment by gabrielamartinezch** [comment]
Entendido. Muchas gracias, Edo.

**Comment by EduardoHernandezGuzman** [comment]
Buen trabajo... A por el siguiente!!!
